version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sudoku-solver"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1crgidj5yvlok"
s3_prefix = "sudoku-solver"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

